#!/usr/bin/python3
import random
number = random.randint(-10, 10)
if number < 0:
    print('{:d}'.format(number) + ' is a negative')
elif number > 0:
    print('{:d}'.format(number) + ' is positive')
else:
    printf('{:d}'.format(number) + ' is zero')
